// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/franciscoalarcon/Desktop/SPRING 2024/Senior Design/EasyBites/EasyBites_FrontEnd_Mobile/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/franciscoalarcon/Desktop/SPRING 2024/Senior Design/EasyBites/EasyBites_FrontEnd_Mobile/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('EasyBites', appParameters);
});
require('/Users/franciscoalarcon/Desktop/SPRING 2024/Senior Design/EasyBites/EasyBites_FrontEnd_Mobile/index.android.js');